# Generated by Django 3.2.13 on 2022-06-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConcepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='doctors_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConcepts.doctor'),
        ),
    ]
