# Generated by Django 3.2.13 on 2022-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConcepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
