# Generated by Django 3.2.13 on 2022-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConcepts', '0002_alter_concept_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept_type',
            name='concept_type_name',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('lab test', 'Lab test')], max_length=50),
        ),
    ]
