# Generated by Django 3.2.13 on 2022-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConcepts', '0003_alter_concept_type_concept_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('lab test', 'Lab test')], default='diagnosis', max_length=50),
        ),
        migrations.AlterField(
            model_name='concept_type',
            name='concept_type_name',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('lab test', 'Lab test')], default='diagnosis', max_length=50),
        ),
    ]
